SRCS	 = l_main.c\
	   l_input.c\
	   l_print.c\
	   l_rprint.c

OBJS	 = l_main.o\
	   l_input.o\
	   l_print.o\
	   l_push.o\
	   l_rprint.o\
	   l_pop.o

list:	   $(OBJS)
	   g++ $(OBJS) -o list.exe

$(OBJS):	l_head.h
